listimoveis/imoveis/urls.py
from django.conf.urls import url

from listimoveis.imoveis.views import new, detail, alter, update, delete

urlpatterns = [
    url(r'^$', new, name='imoveis'),
    url(r'^(?P<slug>[\w-]+)/$', detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/alter$', alter, name='alter'),
    url(r'^(?P<slug>[\w-]+)/alter/salve$', update, name='alter'),
    url(r'^(?P<slug>[\w-]+)/delete$', delete, name='delete'),
]

listimoveis/login/urls.py
from django.conf.urls import url

from listimoveis.login.views import new, call_logout

urlpatterns = [
    url(r'^$', new, name='login'),
    url(r'^logout/$', call_logout, name='logout'),
]

listimoveis/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from listimoveis.core.views import home, search

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^$', search, name='search'),
    url(r'^login/', include('listimoveis.login.urls', namespace='login')),
    url(r'^imoveis/', include('listimoveis.imoveis.urls', namespace='imoveis')),

    url(r'^admin/', admin.site.urls),
]

listimoveis/imoveis/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from django.utils.safestring import mark_safe

from listimoveis.imoveis.validators import validate_cep


class Imovel(models.Model):
    name = models.CharField('nome', max_length=255)
    address = models.CharField('endereço', max_length=255)
    cep = models.CharField('cep', validators=[validate_cep], max_length=8)
    slug = models.SlugField('slug')
    photo = models.ImageField('foto', upload_to='imovel/%m%d%y%H%M%S/')
    description = models.TextField('descrição', blank=True)
    created_at = models.DateTimeField('criado em', auto_now_add = True)

    class Meta:
        verbose_name_plural = 'imóveis'
        verbose_name = 'imóvel'
        ordering = ('-created_at',)

    def __str__(self):
        return self.name

    def image_tag(self):
        return mark_safe('<img src="%s" width="150" height="150" />' % (self.photo.url))
    image_tag.short_description = 'Foto'

listimoveis/imoveis/forms.py
from django import forms
from listimoveis.imoveis.models import Imovel


class ImoveisForm(forms.ModelForm):
    photo = forms.ImageField(label='Foto')

    class Meta:
        model = Imovel
        fields = ['name', 'address', 'photo', 'description', 'cep', 'slug']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control jqName'}),
            'address': forms.TextInput(attrs={'class': 'form-control jqAddress'}),
            'cep': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Somente números', 'maxlength': '8'}),
            'description': forms.Textarea(attrs={'class':'form-control', 'rows': '3'}),
            'slug': forms.TextInput(attrs={'class': 'form-control jqSlug'}),
        }

listimoveis/login/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), label='Nome')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}), label='Senha')

listimoveis/core/views.py
from django.shortcuts import render

from listimoveis.imoveis.models import Imovel


def home(request):
    if request.method == 'GET':
        try:
            q = request.GET.get('q', None)
        except:
            q = None

        if q:
            return search(request, q)

        imoveis = Imovel.objects.all().order_by('-created_at')[:9]
        return render(request, 'index.html', {'imoveis': imoveis})


def search(request, search):
    try:
        imovel_busca = Imovel.objects.all().filter( address__contains=search )
        if not imovel_busca:
            return render(request, 'index.html', {'error': True})
    except:
        return render(request, 'index.html', {'error': True})

    try:
        cep = imovel_busca[0].cep[:5]
        imoveis_rel = Imovel.objects.all().filter( cep__contains=cep )
        print(len(imovel_busca) + len(imoveis_rel))
        print(len(imovel_busca))
        if (len(imovel_busca) * 2) == (len(imovel_busca) + len(imoveis_rel)):
            return render(request, 'index.html', {'imoveis': imovel_busca, 'alert': True})
    except:
        return render(request, 'index.html', {'imoveis': imovel_busca, 'alert': True})

    imoveis = list()
    for i in imovel_busca:
        imoveis.append(i)
    for i in imoveis_rel:
        if i not in imoveis:
            imoveis.append(i)
    return render(request, 'index.html', {'imoveis': imoveis})

listimoveis/imoveis/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url as r, get_object_or_404
from listimoveis.imoveis.forms import ImoveisForm
from listimoveis.imoveis.models import Imovel


def new(request):
    if request.method == 'POST':
        return create(request)
    return empty_form(request)


def empty_form(request):
    return render(request, 'imoveis/imovel-form.html', {'form': ImoveisForm()})


def create(request):
    form = ImoveisForm(request.POST, request.FILES)
    if not form.is_valid():
        return render(request, 'imoveis/imovel-form.html', {'form': form})

    imovel = form.save()

    return HttpResponseRedirect(r('home'))


def detail(request, slug):
    imovel = get_object_or_404(Imovel, slug=slug)
    return render(request, 'imoveis/imovel_detail.html', {'imovel': imovel})


def alter(request, slug):
    if request.method == 'POST':
        return update(request, slug)
    return update_form(request, slug)

def delete(request, slug):
    data = get_object_or_404(Imovel, slug=slug)
    data.delete()
    return HttpResponseRedirect(r('home'))


def update_form(request, slug):
    imovel = get_object_or_404(Imovel, slug=slug)
    form = ImoveisForm(initial={'name': imovel.name, 'address': imovel.address, 'cep': imovel.cep,
                                'slug': imovel.slug, 'photo': imovel.photo, 'description': imovel.description})
    return render(request, 'imoveis/imovel_alter.html', {'form': form})


def update(request, slug):
    data = get_object_or_404(Imovel, slug=slug)
    form = ImoveisForm(request.POST, request.FILES)
    if not form.is_valid():
        return render(request, 'imoveis/imovel_alter.html', {'form': form})
    imovel = form.save(commit=False)
    imovel.created_at = data.created_at
    imovel.id = data.pk
    imovel.save()

    return HttpResponseRedirect(r('home'))

listimoveis/login/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url as r

from listimoveis.login.forms import LoginForm


def new(request):
    if not request.user.is_authenticated():
        if request.method == 'POST':
            return create(request)
        return empty_form(request)
    else:
        return call_cms(request)


def create(request):
    form = LoginForm(request.POST)

    if not form.is_valid():
        return render(request, 'login/login.html', {'form': form})

    user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])

    if user is not None:
        login(request, user)
        return call_cms(request)
    else:
        return render(request, 'login/login.html', {'form': form})


def empty_form(request):
    return render(request, 'login/login.html', {'form': LoginForm()})


def call_cms(request):
    return HttpResponseRedirect(r('home'))


def call_logout(request):
    logout(request)
    return HttpResponseRedirect(r('login:login'))

listimoveis/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}List Imóveis - Lista de Imóveis Disponíveis{% endblock title %}</title>

	<link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static 'css/base.css' %}" rel="stylesheet" />

    {% block style %}
    {% endblock style %}

</head>
<body>
	<div class="container-fluid" id="jqHome">
	<!-- MENU -->
	 <nav class="navbar navbar-default navbar-fixed-top">
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <a href="{% url 'home' %}" class="brand name-menu">List Imóveis</a>

	        </div>
	        <div id="navbar" class="navbar-collapse collapse">
		        <ul class="nav navbar-nav navbar-right">
                    {% if not request.user.is_authenticated %}
                         <li><a href="{% url 'login:login' %}">Login</a></li>
                    {% else %}
                        <li><a href="{% url 'imoveis:imoveis' %}">Cadastrar</a></li>
                        <li><a href="{% url 'login:logout' %}">Sair</a></li>
                    {% endif %}
		        </ul>
	        </div>
	      </div>
	    </nav>
	<!-- MENU -->

	<!-- INTRODUÇÃO -->
		<div class="row div-introducao">
			<div class="container">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<a href="{% url 'home' %}" class="brand logo-menu"><h1><strong>List Imóveis</strong></h1></a>
				</div>
			</div>
			<div class="div-sub">
				<div class="container">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<h2>Listagem de Imóveis para locação</h2>
					</div>
				</div>
			</div>
		</div>
	<!-- INTRODUÇÃO -->
        {% block content %}
        {% endblock content %}

	<!-- RODAPÉ -->
	<footer class="row div-rodape">
        <div class="container">
            <div class="div-conteudo">
                <nav>
                    <ul>
                        <li class="li-home"><a href="{% url 'home' %}">Home</a></li>
                        <li class="li-barra">|</li>
                        {% if not request.user.is_authenticated %}
                            <li><a href="{% url 'login:login' %}">Login</a></li>
                        {% else %}
                            <li><a href="{% url 'imoveis:imoveis' %}">Cadastrar</a></li>
                            <li class="li-barra">|</li>
                            <li><a href="{% url 'login:logout' %}">Sair</a></li>
                        {% endif %}
                    </ul>
                </nav>
           </div>
        </div>
        <div class="div-copyright">
            <div class="container">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <p class="text-center">© 2016 List Imóveis - Lista de Imóveis Disponíveis</p>
                </div>
            </div>
        </div>
	</footer>
	<!-- RODAPÉ -->

	</div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>

    {% block script %}
    {% endblock script %}

</body>
</html>

listimoveis/core/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
<link href="{% static 'css/imoveil-menu.css' %}" rel="stylesheet" />
{% endblock style %}

{% block content %}
<!-- OVERVIEW -->
<div class="row">
    <div class="container">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <form type="get" action="." class="form-inline" style="margin: 15px 0 0 0">
            <div class="form-group center-block">
            <input  id="search_box"  class="form-control" type="text" name="q"  placeholder="Buscar..." >
            </div>
                <button id="search_submit" class="btn btn-default" type="submit" >Enviar</button>
        </form>
    </div>
        {% if alert %}
            <div class="alert alert-warning">Não foram localizadas outras casa próximas ao endereço!</div>
        {% elif error %}
            <div class="alert alert-danger">Nenhuma casa foi encontrada!</div>
        {% endif %}
        {% for imovel in imoveis %}
            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                <a href="imoveis/{{ imovel.slug }}" class="center-block border">
                    <h3 class="text-center"><strong>{{ imovel.name }}</strong></h3>
                    <img src="{{ imovel.photo.url }}" class="img-responsive img-rounded center-block" alt="{{ imovel.name }}" />
                    <h4 class="text-center">{{ imovel.address }}</h4>
                    <p class="text-center">{{ imovel.description }}</p>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
<!-- OVERVIEW -->
{% endblock content %}

listimoveis/core/templates/templates/login/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}
<!-- OVERVIEW -->
<div class="row">
    <div class="container">
        <h1>Login</h1>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
             <form method="post">
                 {% csrf_token %}
                 {{ form.non_field_errors }}
                 <div class="form-group">
                    <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                        {{ form.username.errors }}
                        {{ form.username }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
                        {{ form.password.errors }}
                        {{ form.password }}
                 </div>
                    <input type="submit" class="btn btn-default" value="Entrar"/>
             </form>
        </div>
    </div>
</div>
<!-- OVERVIEW -->
{% endblock content %}

listimoveis/imoveis/templates/imoveis/imovel-form.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Cadastrar Imóvel{% endblock title %}

{% block content %}
<!-- OVERVIEW -->
<div class="row">
    <div class="container">
        <h1>Cadastrar</h1>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
             <form method="post" id="jqForm"  enctype="multipart/form-data">
                 {% csrf_token %}
                 {{ form.non_field_errors }}
                 {{ form.slug.as_hidden }}
                 <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                        {{ form.name.errors }}
                        {{ form.name }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.address.id_for_label }}">{{ form.address.label }}</label>
                        {{ form.address.errors }}
                        {{ form.address }}

                 <div class="form-group">
                    <label for="{{ form.cep.id_for_label }}">{{ form.cep.label }}</label>
                        {{ form.cep.errors }}
                        {{ form.cep }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
                        {{ form.description.errors }}
                        {{ form.description }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.photo.id_for_label }}">{{ form.photo.label }}</label>
                        {{ form.photo.errors }}
                        {{ form.photo }}
                 </div>
                 <input type="submit" class="btn btn-primary pull-right" value="Salvar"/>
             </form>
        </div>
    </div>
</div>
<!-- OVERVIEW -->
{% endblock content %}

{% block script %}
<script src="{% static 'js/form-imovel.js' %}"></script>
{% endblock script %}

listimoveis/imoveis/templates/imoveis/imovel_alter.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Alterar Imóvel{% endblock title %}

{% block content %}
<!-- OVERVIEW -->
<div class="row">
    <div class="container">
        <h1>Alterar</h1>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
             <form method="POST" id="jqForm" enctype="multipart/form-data">
                 {% csrf_token %}
                 {{ form.non_field_errors }}
                 <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                        {{ form.name.errors }}
                        {{ form.name }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.slug.id_for_label }}">{{ form.slug.label }}</label>
                        {{ form.slug.errors }}
                        {{ form.slug }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.address.id_for_label }}">{{ form.address.label }}</label>
                        {{ form.address.errors }}
                        {{ form.address }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.cep.id_for_label }}">{{ form.cep.label }}</label>
                        {{ form.cep.errors }}
                        {{ form.cep }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
                        {{ form.description.errors }}
                        {{ form.description }}
                 </div>
                 <div class="form-group jqPhotoGrup">
                    <label for="{{ form.photo.id_for_label }}">{{ form.photo.label }}</label>
                        {{ form.photo.errors }}
                        {{ form.photo }}
                 </div>
                 <input type="submit" class="btn btn-primary pull-right jqBtn" value="Salvar"/>
             </form>
        </div>
    </div>
</div>
<!-- OVERVIEW -->
{% endblock content %}

listimoveis/imoveis/templates/imoveis/imovel_detail.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
<link href="{% static 'css/imoveil-menu.css' %}" rel="stylesheet" />
{% endblock style %}

{% block content %}
    <!-- OVERVIEW -->
<div class="row">
    <div class="container">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="center-block border-detail">
                <h3 class="text-center"><strong>{{ imovel.name }}</strong></h3>
                <img src="{{ imovel.photo.url }}" class="img-responsive img-rounded center-block" alt="{{ imovel.name }}" />
                <h4 class="text-center">{{ imovel.address }}</h4>
                <p class="text-center">{{ imovel.description }}</p>
            </div>
            {% if request.user.is_authenticated %}
                <a href="delete"  class="btn btn-danger pull-right">Excluir</a>
                <a href="alter" style="margin-right: 5px" class="btn btn-warning pull-right">Alterar</a>
            {% endif %}
        </div>
    </div>
</div>
<!-- OVERVIEW -->
{% endblock content %}

listimoveis/login/templates/login/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}
<!-- OVERVIEW -->
<div class="row">
    <div class="container">
        <h1>Login</h1>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
             <form method="post">
                 {% csrf_token %}
                 {{ form.non_field_errors }}
                 <div class="form-group">
                    <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                        {{ form.username.errors }}
                        {{ form.username }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
                        {{ form.password.errors }}
                        {{ form.password }}
                 </div>
                    <input type="submit" class="btn btn-default" value="Entrar"/>
             </form>
        </div>
    </div>
</div>
<!-- OVERVIEW -->
{% endblock content %}